### PR TITLE
[WIP] Switch from JSHint to ESLint

### PR DESCRIPTION
**Pull request by martndemus**
So we don't have to use the annoying JSHint guards everywhere
Addresses #25

To-Do:
- [x] Get ember-cli/ember-cli-qunit#87 merged
- [ ] Submit patches to linters that add rules specific to decorators (babel/eslint-plugin-babel#28)

### CODE REVIEW

**Comment by martndemus** [comment]
After some toying with the supposed faulty `unused variable` warnings. I think the warnings are actually correct.

Take the following example:

```javascript
var foo = 42;
var obj = { foo };
obj.foo; 
// => 42
```

Which isn't really different from

```javascript
var foo = 42
var obj = { @readOnly foo }
obj.foo
// => 42
```

So things like:
```javascript
var Model = DS.Model.extend({
  @attr firstName,
  @attr({ defaultTo: 'blue' }) lastName
});
```

can cause subtle bugs.

So although it doesn't look that great, it would be more correct to write:
```javascript
var Model = DS.Model.extend({
  @attr firstName: null,
  @attr({ defaultTo: 'blue' }) lastName: null
});
```

**Comment by SirZach** [comment]
bump?

**Comment by martndemus** [comment]
Thanks for reminding me, I'll try to work on this soon™

**Comment by pzuraq** [comment]
This was superceded by #106

**Pull request closed without merging**
