### PR TITLE
fix(object): computed: require getter, don't require but honor setter return value

### LINKED ISSUE #140: @computed: disallow lonely setter, ignore its return value, always use getter return value as property value
https://github.com/rwjblue/ember-decorators/pull/137#discussion_r129347557

Apparently setting a `@computed` property with a setter will always set that CP to `undefined` [since the return value is not passed on](https://github.com/rwjblue/ember-decorators/blob/8a36530c238e823ce9bce8259bf604606aa8ecfa/addon/object/index.js#L173).

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes #140.

### CODE REVIEW

**Comment by rwjblue** [comment]
I wonder if we can take this opportunity to remove the wackiness here. Specifically, we could do something like:

```js
    return emberComputed(...params, {
      get,
      set(key, value) {
        let ret = set.call(this, value);
        if (ret === undefined) {
          return get.call(this);
        }
      }
    });
```

**Comment by buschtoens** [comment]
Assuming that users will never intentionally `return undefined;`, this seems like a good idea.

**Comment by buschtoens** [comment]
However, this would only work for ES6 getters and setters then. I think we should rather be consistent.

**Comment by rwjblue** [comment]
We are already in an uncanny valley (using getters and setters opts you into a completely different world than using methods), and I think we will have to dig out via deprecations and a major version bump...

Specifically, I think we should drop support for the "method" version:

```js
class Foo extends Ember.Object {
  @computed
  derp() {}
}
```

And only support the getter and/or setter versions:

```js
class Foo extends Ember.Object {
  @computed
  get derp() {}
}
```

If we do this, then my proposed change is not harmful or inconsistent (there would just be one way to do it). 

---

Also, FWIW, we want to make this change in Ember itself also.  Basically, deprecating returning `undefined` for a given set when the getter for the CP returns something other than `undefined`.

**Comment by rwjblue** [comment]
> Assuming that users will never intentionally return undefined;, this seems like a good idea.

Even if they do `return undefined` on purpose, it is still ok as long as their getter matches (and we can add a warning/deprecation/assertion/etc if they don't).

**Comment by pzuraq** [comment]
This _is_ what `null` is for after all 😛 I think it makes sense. That major version bump is going to be coming either way, and I agree that getters/setters seem like the path forward, so we can experiment a little with this I think.

**Comment by buschtoens** [comment]
Ah okay. I didn't know about these plans. Makes sense.

I'll add it to the PR.

**Comment by buschtoens** [comment]
Would you like a warning when a setter returns `undefined` and there is no corresponding getter?

**Comment by pzuraq** [comment]
I think a warning would make sense, I can't think of a case where you would want to use a computed `setter` without a `getter` over just a plain ES setter. Like, it could clear out the cached value whenever a key updates? I think there would be better ways to accomplish that.

Actually thinking this through more, we should probably mirror the behavior of ES getters and setters and throw if a user tries to get without a getter defined or set without a setter defined.

**Comment by buschtoens** [comment]
Thinking about it, since the return value of an [ES6 setter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) is ignored and we force users to have a getter as well, we should also ignore the return value and just return the getter's value, i.e.:

```js
    return emberComputed(...params, {
      get,
      set(key, value) {
        const ret = set.call(this, value);
        warn(`Return values of ES6 setters are ignored.`, typeof ret === 'undefined');
        return get.call(this);
      }
    });
```

**Comment by pzuraq** [comment]
I'm on board with requiring a getter for computeds, there are no use cases I can think of where a plain ES6 setter without a getter makes sense as a computed. _Technically_ you could do:

```javascript
const Foo = Ember.Object.extend({
  bar: computed({
    set(key, val) {
      return val;
    }
  })
});

foo.set('val', 1);
console.log(foo.get('val')); // 1
```

But I think that's horribly, terribly awful behavior that we shouldn't enable.

I also agree that we should enable ES6 setter semantics - essentially, if you have an ES6 getter + setter and you want to mark them as a computed, you should be able to do so with no changes. However, I think we should consider providing an opt-out by still accepting the return value if it exists. This makes sense since it would essentially be providing additional functionality on top of ES6 setters, which decorators are able to do. So:

```javascript
set (key, value) {
  assert(`you must provide a setter in order to set '${key}' as a computed property`, typeof set === 'function');

  let ret = set.call(this, value);
  return ret === undefined ? get.call(this) : ret;
}
```

Added an assertion, the code already implies that `set` must exist but this will give users a nicer error message.

**Comment by pzuraq** [comment]
@rwjblue thoughts?

**Comment by pzuraq** [comment]
we can also probably eliminate the need for creating a setter function if one does not exist:

```
import { DEBUG } from '@glimmer/env';

...

let { get, set } = desc;

assert(`Using @computed for only a setter does not make sense. Add a getter for '${key}' as well or remove the @computed decorator.`, typeof get === 'function');

// Unset the getter and setter so the descriptor just has a plain value
desc.get = undefined;
desc.set = undefined;

let setter;

if (typeof set === 'function') {
  setter = function(key, value) {
    let ret = set.call(this, value);
    return ret === undefined ? get.call(this) : ret;
  };
} else if (DEBUG) {
  setter = function() {
    assert(`you must provide a setter in order to set '${key}' as a computed property`, typeof set === 'function');
  };
}

// Use a standard ember computed since getter/setter arrity is restricted,
// meaning ember-macro-helpers doesn't provide any benefit
return emberComputed(...params, { get, set: setter });
```

**Comment by rwjblue** [comment]
Agreed, https://github.com/rwjblue/ember-decorators/pull/141#issuecomment-318022389 seems like the right way forward to me also.

**Comment by pzuraq** [comment]
👍 Looks good! Thanks for getting this over the line @buschtoens!

**Comment by buschtoens** [comment]
Glad I could help. :smiley:

**Pull request merged**
